<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Import-Libraries" data-toc-modified-id="Import-Libraries-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Import Libraries</a></span></li><li><span><a href="#Create-df" data-toc-modified-id="Create-df-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Create df</a></span></li><li><span><a href="#Feature-Engineering" data-toc-modified-id="Feature-Engineering-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Feature Engineering</a></span><ul class="toc-item"><li><span><a href="#Function-for-Submission" data-toc-modified-id="Function-for-Submission-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Function for Submission</a></span></li><li><span><a href="#Engineer-Single-Stock" data-toc-modified-id="Engineer-Single-Stock-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Engineer Single Stock</a></span></li><li><span><a href="#Define-Model" data-toc-modified-id="Define-Model-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Define Model</a></span></li><li><span><a href="#Train-and-Test-dfs" data-toc-modified-id="Train-and-Test-dfs-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Train and Test dfs</a></span></li><li><span><a href="#Set-Params" data-toc-modified-id="Set-Params-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>Set Params</a></span></li><li><span><a href="#Fit-Model" data-toc-modified-id="Fit-Model-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>Fit Model</a></span></li><li><span><a href="#Generate-Predictions" data-toc-modified-id="Generate-Predictions-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Generate Predictions</a></span></li></ul></li><li><span><a href="#Submission-df" data-toc-modified-id="Submission-df-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Submission df</a></span><ul class="toc-item"><li><span><a href="#Generate-Small-df-Predictions" data-toc-modified-id="Generate-Small-df-Predictions-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Generate Small df Predictions</a></span></li></ul></li><li><span><a href="#Practice-Submission" data-toc-modified-id="Practice-Submission-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Practice Submission</a></span></li></ul></div>

# Import Libraries

In [1]:
# Import all packages that I might need:
import sys 
import numpy as np # linear algebra
from scipy.stats import randint
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv), data manipulation as in SQL
import matplotlib.pyplot as plt # this is used for the plot the graph 
import seaborn as sns # used for plot interactive graph. 
from sklearn.model_selection import train_test_split # to split the data into two parts
from sklearn.model_selection import KFold # use for cross validation
from sklearn.preprocessing import StandardScaler # for normalization
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline # pipeline making
from sklearn.model_selection import cross_val_score
from sklearn.feature_selection import SelectFromModel
from sklearn import metrics # for the check the error and accuracy of the model
from sklearn.metrics import mean_squared_error,r2_score
from scipy import stats
import IPython
import IPython.display

## for Deep-learing:
import keras
from keras.layers import Dense
from keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import SGD 
from keras.callbacks import EarlyStopping
from keras.utils import np_utils
import itertools
from keras.layers import LSTM
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Dropout
import tensorflow as tf
from tensorflow.keras.metrics import RootMeanSquaredError, MeanAbsoluteError

# Create df

In [22]:
# Create dataframes
prices = pd.read_csv(
    r'/Users/jimpetoskey/Documents/Flatiron/phase5/data/stock_prices.csv')
prices_2 = pd.read_csv(
    r'/Users/jimpetoskey/Documents/Flatiron/phase5/data/stock_prices 2.csv')

In [3]:
# make copy of prices
df1 = prices.copy()

# Look at top-performing stocks, choose top-performer to model
df1.sort_values(by='Target', ascending=False)

df1.head(5)

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
0,20170104_1301,2017-01-04,1301,2734.0,2755.0,2730.0,2742.0,31400,1.0,NaN,False,0.000730
1,20170104_1332,2017-01-04,1332,568.0,576.0,563.0,571.0,2798500,1.0,NaN,False,0.012324
2,20170104_1333,2017-01-04,1333,3150.0,3210.0,3140.0,3210.0,270800,1.0,NaN,False,0.006154
3,20170104_1376,2017-01-04,1376,1510.0,1550.0,1510.0,1550.0,11300,1.0,NaN,False,0.011053
4,20170104_1377,2017-01-04,1377,3270.0,3350.0,3270.0,3330.0,150800,1.0,NaN,False,0.003026

In [4]:
# Pull one stock's values for given stock from stock_prices
values8103 = df1.loc[df1['SecuritiesCode'] == 8103] 
values8103_copy = values8103.copy()
values8103_copy.head(2)

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
1450,20170104_8103,2017-01-04,8103,406.0,413.0,395.0,413.0,82600,1.0,NaN,False,-0.024213
3315,20170105_8103,2017-01-05,8103,415.0,419.0,408.0,413.0,57500,1.0,NaN,False,-0.002481

In [5]:
values8103_copy

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag,Target
1450,20170104_8103,2017-01-04,8103,406.0,413.0,395.0,413.0,82600,1.0,NaN,False,-0.024213
3315,20170105_8103,2017-01-05,8103,415.0,419.0,408.0,413.0,57500,1.0,NaN,False,-0.002481
5180,20170106_8103,2017-01-06,8103,404.0,410.0,401.0,403.0,60600,1.0,NaN,False,-0.017413
7045,20170110_8103,2017-01-10,8103,404.0,408.0,398.0,402.0,41800,1.0,NaN,False,0.007595
8910,20170111_8103,2017-01-11,8103,405.0,405.0,390.0,395.0,56200,1.0,NaN,False,0.010050
...,...,...,...,...,...,...,...,...,...,...,...,...
2324104,20211129_8103,2021-11-29,8103,829.0,843.0,825.0,828.0,590800,1.0,NaN,False,0.008547
2326104,20211130_8103,2021-11-30,8103,839.0,846.0,818.0,819.0,578100,1.0,NaN,False,0.000000
2328104,20211201_8103,2021-12-01,8103,822.0,833.0,819.0,826.0,443000,1.0,NaN,False,0.015738
2330104,20211202_8103,2021-12-02,8103,828.0,832.0,818.0,826.0,407500,1.0,NaN,False,0.004768
2332104,20211203_8103,2021-12-03,8103,825.0,840.0,825.0,839.0,438200,1.0,NaN,False,0.010676

# Feature Engineering

In [6]:
def feature_eng(train):
    
    # Add Lag Features
    lag_features = ["High", "Low", "Volume", "Close", "Open"]
    df_rolled_7d = train[lag_features].rolling(window=4, min_periods=0)
    df_mean_7d = df_rolled_7d.mean().shift(1).reset_index().astype(np.float32)
    df_mean_7d = df_mean_7d.drop('index', axis=1)
    df_mean_7d = df_mean_7d.fillna(0)
    df_mean_7d = df_mean_7d.round(2)
    df_mean_7d['High_lag_1'] = df_mean_7d['High']
    df_mean_7d['Open_lag_1'] = df_mean_7d['Open']
    df_mean_7d['Close_lag_1'] = df_mean_7d['Close']
    df_mean_7d['Volume_lag_1'] = df_mean_7d['Volume']
    df_mean_7d['Low_lag_1'] = df_mean_7d['Low']
    df_mean_7d = df_mean_7d.drop(["High", "Low", "Volume", "Close", "Open"], axis=1)
    train = train.reset_index(drop=True)
    train = pd.concat([train, df_mean_7d], axis=1)
    
    # Set Datetime index
    train['Date'] = pd.to_datetime(train['Date'], format='%Y/%m/%d', errors='coerce')
    mask = train['Date'].isnull()
    train.loc[mask, 'Date'] = pd.to_datetime(train['Date'], format='%Y/%m/%d',
                                                 errors='coerce')
    train = train.set_index('Date')
    
    # Drop irrelevant columns for training
    train = train.drop(
                        ['RowId', 
                         'SecuritiesCode', 
                         'ExpectedDividend', 
                         'SupervisionFlag',
                         'AdjustmentFactor'], axis=1)
    
    # Bool to int for SupervisionFlag
    #train["SupervisionFlag"] = train["SupervisionFlag"].astype(int)
    
    # Forward, then backward fill missing values in cols
    cols = ['Open', 'High', 'Low', 'Close', 'Target']
    train.loc[:,cols] = train.loc[:,cols].ffill()
    train.loc[:,cols] = train.loc[:,cols].bfill()
    
    # Replace missing values in ExpectedDividend with 0
    #train['ExpectedDividend'] = train['ExpectedDividend'].fillna(0)
    
    # Add Spread Features
    train['Daily_Spread'] = train['Close'] - train['Open']
    train['Daily_Max_Min'] = train['High'] - train['Low']
    train['1_Day_Spread'] = train['Close'].diff()
    train['2_Day_Spread'] = train['Close'].diff(periods=2)
    train['1_Week_Spread'] = train['Close'].diff(periods=5)
    train['MA_Prior_1day'] = train['Close'].diff(periods= -1)
    train['MA_Prior_2day'] = train['Close'].diff(periods= -2)
    train = train.fillna(0)
    train['MA_Prior_diff'] = train['MA_Prior_1day'] - train['MA_Prior_2day']
    
    # Fill missing values with 0
    train = train.fillna(0)
        
    # Add rolling ratio of mean/std of forward 1 day return
    indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=5)
    train['ExPost_SR'] = (train['MA_Prior_diff'].rolling(
        window=indexer, min_periods=1).mean())/(
        train['MA_Prior_diff'].std())
    
    # MinMax Scale columns (0-1 scale)   
    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(train)
    train_cols = train.columns.values.tolist()
    trained = pd.DataFrame(data=scaled, columns=train_cols, index=train.index)
    
    # Fill missing values with 0
    #train = train.fillna(0)
    
    return trained

## Function for Submission
* No Target is present in final submission df, so it needs to be removed from feature_eng() function.

In [36]:
def featuring(train):
    
    # Add Lag Features
    lag_features = ["High", "Low", "Volume", "Close", "Open"]
    df_rolled_7d = train[lag_features].rolling(window=4, min_periods=0)
    df_mean_7d = df_rolled_7d.mean().shift(1).reset_index().astype(np.float32)
    df_mean_7d = df_mean_7d.drop('index', axis=1)
    df_mean_7d = df_mean_7d.fillna(0)
    df_mean_7d = df_mean_7d.round(2)
    df_mean_7d['High_lag_1'] = df_mean_7d['High']
    df_mean_7d['Open_lag_1'] = df_mean_7d['Open']
    df_mean_7d['Close_lag_1'] = df_mean_7d['Close']
    df_mean_7d['Volume_lag_1'] = df_mean_7d['Volume']
    df_mean_7d['Low_lag_1'] = df_mean_7d['Low']
    df_mean_7d = df_mean_7d.drop(["High", "Low", "Volume", "Close", "Open"], axis=1)
    train = train.reset_index(drop=True)
    train = pd.concat([train, df_mean_7d], axis=1)
    
    # Set Datetime index
    train['Date'] = pd.to_datetime(train['Date'], format='%Y/%m/%d', errors='coerce')
    mask = train['Date'].isnull()
    train.loc[mask, 'Date'] = pd.to_datetime(train['Date'], format='%Y/%m/%d',
                                                 errors='coerce')
    train = train.set_index('Date')
    
    # Drop irrelevant columns for training
    train = train.drop(
                        ['RowId', 
                         'SecuritiesCode', 
                         'ExpectedDividend', 
                         'SupervisionFlag',
                         'AdjustmentFactor'], axis=1)
    
    # Bool to int for SupervisionFlag
    #train["SupervisionFlag"] = train["SupervisionFlag"].astype(int)
    
    # Forward, then backward fill missing values in cols
    cols = ['Open', 'High', 'Low', 'Close']
    train.loc[:,cols] = train.loc[:,cols].ffill()
    train.loc[:,cols] = train.loc[:,cols].bfill()
    
    # Replace missing values in ExpectedDividend with 0
    #train['ExpectedDividend'] = train['ExpectedDividend'].fillna(0)
    
    # Add Spread Features
    train['Daily_Spread'] = train['Close'] - train['Open']
    train['Daily_Max_Min'] = train['High'] - train['Low']
    train['1_Day_Spread'] = train['Close'].diff()
    train['2_Day_Spread'] = train['Close'].diff(periods=2)
    train['1_Week_Spread'] = train['Close'].diff(periods=5)
    train['MA_Prior_1day'] = train['Close'].diff(periods= -1)
    train['MA_Prior_2day'] = train['Close'].diff(periods= -2)
    train = train.fillna(0)
    train['MA_Prior_diff'] = train['MA_Prior_1day'] - train['MA_Prior_2day']
    
    # Fill missing values with 0
    train = train.fillna(0)
        
    # Add rolling ratio of mean/std of forward 1 day return
    indexer = pd.api.indexers.FixedForwardWindowIndexer(window_size=5)
    train['ExPost_SR'] = (train['MA_Prior_diff'].rolling(
        window=indexer, min_periods=1).mean())/(
        train['MA_Prior_diff'].std())
    
    # MinMax Scale columns (0-1 scale)   
    scaler = MinMaxScaler()
    scaled = scaler.fit_transform(train)
    train_cols = train.columns.values.tolist()
    trained = pd.DataFrame(data=scaled, columns=train_cols, index=train.index)
    
    # Fill missing values with 0
    #train = train.fillna(0)
    
    return trained

## Engineer Single Stock

In [7]:
norm_df = feature_eng(values8103_copy)
norm_df.head(2)

,Open,High,Low,Close,Volume,Target,High_lag_1,Open_lag_1,Close_lag_1,Volume_lag_1,Low_lag_1,Daily_Spread,Daily_Max_Min,1_Day_Spread,2_Day_Spread,1_Week_Spread,MA_Prior_1day,MA_Prior_2day,MA_Prior_diff,ExPost_SR
Date,,,,,,,,,,,,,,,,,,,,
2017-01-04,0.069547,0.061787,0.071101,0.073248,0.007137,0.148399,0.000000,0.000000,0.000000,0.000000,0.000000,0.405405,0.060403,0.238095,0.256112,0.315126,0.761905,0.755530,0.219048,0.305882
2017-01-05,0.079031,0.067490,0.086009,0.073248,0.004968,0.177205,0.321714,0.333539,0.338733,0.017657,0.335742,0.375000,0.036913,0.238095,0.256112,0.315126,0.780952,0.756694,0.236190,0.308403

In [8]:
# Split df into train/test
column_indices = {name: i for i, name in enumerate(norm_df.columns)}

n = len(norm_df)
train_df = norm_df[0:int(n*0.9)]
test_df = norm_df[int(n*0.9):]

num_features = norm_df.shape[1]

In [9]:
print('Training Shape:', train_df.shape)
print('Test Shape:', test_df.shape)

Training Shape: (1081, 20)
Test Shape: (121, 20)

## Define Model

In [10]:
def cnnpred_2d(seq_len=60, n_features=82, n_filters=(8,8,8), droprate=0.1):
    "2D-CNNpred model according to the paper"
    model = Sequential([
        Input(shape=(seq_len, n_features, 1)),
        Conv2D(n_filters[0], kernel_size=(1, n_features), activation="relu"),
        Conv2D(n_filters[1], kernel_size=(3,1), activation="relu"),
        MaxPool2D(pool_size=(2,1)),
        Conv2D(n_filters[2], kernel_size=(3,1), activation="relu"),
        MaxPool2D(pool_size=(2,1)),
        Flatten(),
        Dropout(droprate),
        Dense(1, activation="sigmoid")
    ])
    return model

## Train and Test dfs

In [16]:
x_train = train_df.drop('Target', axis=1)
y_train = train_df['Target']

In [17]:
x_test = test_df.drop('Target', axis=1)
y_test = test_df['Target']

## Set Params

In [ ]:
params = {
	"loss": "mean_squared_error",
	"optimizer": "adam",
	"dropout": 0.2,
	"lstm_units": 90,
	"epochs": 4,
	"batch_size": 128,
	"es_patience" : 10
}

model = get_model(params=params, input_shape=x_train.shape[1])

In [ ]:
es_callback = tf.keras.callbacks.EarlyStopping(monitor='val_root_mean_squared_error',
                                           	mode='min', 
                                            patience=params["es_patience"])

## Fit Model

In [18]:
history = model.fit(
	x_train,
	y_train,
	validation_data=(x_test, y_test),
	epochs=params["epochs"],
	batch_size=params["batch_size"],
	verbose=1,
)

Epoch 1/4
9/9 [==============================] - 22s 580ms/step - loss: 0.0092 - root_mean_squared_error: 0.0957 - mean_absolute_error: 0.0762 - val_loss: 0.0112 - val_root_mean_squared_error: 0.1056 - val_mean_absolute_error: 0.0554
Epoch 2/4
9/9 [==============================] - 2s 202ms/step - loss: 0.0024 - root_mean_squared_error: 0.0488 - mean_absolute_error: 0.0388 - val_loss: 0.0121 - val_root_mean_squared_error: 0.1100 - val_mean_absolute_error: 0.0699
Epoch 3/4
9/9 [==============================] - 2s 199ms/step - loss: 0.0014 - root_mean_squared_error: 0.0376 - mean_absolute_error: 0.0277 - val_loss: 0.0091 - val_root_mean_squared_error: 0.0953 - val_mean_absolute_error: 0.0380
Epoch 4/4
9/9 [==============================] - 2s 217ms/step - loss: 0.0012 - root_mean_squared_error: 0.0348 - mean_absolute_error: 0.0247 - val_loss: 0.0093 - val_root_mean_squared_error: 0.0964 - val_mean_absolute_error: 0.0443

In [115]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_20 (LSTM)              (None, 19, 90)            33120

 dropout_20 (Dropout)        (None, 19, 90)            0

 lstm_21 (LSTM)              (None, 19, 90)            65160

 dropout_21 (Dropout)        (None, 19, 90)            0

 lstm_22 (LSTM)              (None, 19, 90)            65160

 dropout_22 (Dropout)        (None, 19, 90)            0

 lstm_23 (LSTM)              (None, 90)                65160

 dropout_23 (Dropout)        (None, 90)                0

 dense_5 (Dense)             (None, 1)                 91

=================================================================
Total params: 228,691
Trainable params: 228,691
Non-trainable params: 0
_________________________________________________________________

## Generate Predictions

In [116]:
test_out = model.predict(x_test)
test_out

4/4 [==============================] - 2s 30ms/step

array([[0.5310267 ],
       [0.5101439 ],
       [0.507942  ],
       [0.5060973 ],
       [0.51307786],
       [0.505362  ],
       [0.50312555],
       [0.4992654 ],
       [0.48500332],
       [0.51462984],
       [0.5003122 ],
       [0.49230897],
       [0.50018746],
       [0.5030998 ],
       [0.4913771 ],
       [0.4946833 ],
       [0.48863593],
       [0.507826  ],
       [0.50421715],
       [0.50278455],
       [0.4917747 ],
       [0.4894168 ],
       [0.49319217],
       [0.50922626],
       [0.5197172 ],
       [0.51203686],
       [0.51590234],
       [0.5335375 ],
       [0.5112532 ],
       [0.50301397],
       [0.5237717 ],
       [0.51190495],
       [0.54415005],
       [0.5371685 ],
       [0.53488547],
       [0.51719457],
       [0.53938025],
       [0.519142  ],
       [0.5961309 ],
       [0.5548001 ],
       [0.54219186],
       [0.5335692 ],
       [0.54357153],
       [0.5277671 ],
       [0.529916  ],
       [0.51988244],
       [0.52267605],
       [0.5488934 ],
       [0.5258411 ],
       [0.52470857],
       [0.54138863],
       [0.54008484],
       [0.5406912 ],
       [0.5376801 ],
       [0.5311122 ],
       [0.5504824 ],
       [0.54124874],
       [0.5404329 ],
       [0.53811014],
       [0.5671144 ],
       [0.5540057 ],
       [0.5556211 ],
       [0.55336136],
       [0.5527327 ],
       [0.5617624 ],
       [0.5666181 ],
       [0.56589967],
       [0.55637616],
       [0.5665599 ],
       [0.5701922 ],
       [0.56414276],
       [0.55561495],
       [0.58518046],
       [0.5818485 ],
       [0.5721738 ],
       [0.57353574],
       [0.57335204],
       [0.5505513 ],
       [0.55852437],
       [0.5440516 ],
       [0.56165034],
       [0.5565155 ],
       [0.55470496],
       [0.55682683],
       [0.54515624],
       [0.5455553 ],
       [0.6541    ],
       [0.6008322 ],
       [0.5727523 ],
       [0.5810615 ],
       [0.5805601 ],
       [0.56293195],
       [0.56590563],
       [0.55715173],
       [0.5730419 ],
       [0.55587554],
       [0.57271653],
       [0.5647617 ],
       [0.5795317 ],
       [0.56534004],
       [0.5537143 ],
       [0.6215482 ],
       [0.579775  ],
       [0.5558762 ],
       [0.5616141 ],
       [0.5639005 ],
       [0.5541461 ],
       [0.54897237],
       [0.5523072 ],
       [0.5394875 ],
       [0.5318783 ],
       [0.53190607],
       [0.54998773],
       [0.5319524 ],
       [0.53059447],
       [0.5298143 ],
       [0.5118111 ],
       [0.5313842 ],
       [0.53163135],
       [0.5280424 ],
       [0.54011476]], dtype=float32)

In [117]:
y_test

Date
2021-06-09    0.435072
2021-06-10    0.463873
2021-06-11    0.512419
2021-06-14    0.473568
2021-06-15    0.444643
                ...
2021-11-29    0.482756
2021-11-30    0.464397
2021-12-01    0.583816
2021-12-02    0.509564
2021-12-03    0.178624
Name: Target, Length: 121, dtype: float64

# Submission df

In [26]:
col_list = df1['SecuritiesCode'].values.tolist()
small_col_list = col_list[:2]
small_col_list

[1301, 1332]

## Generate Small df Predictions

In [132]:
small_df = pd.DataFrame()

for col in small_col_list:
    # Pull one stock's values for given stock from stock_prices
    smallest = df1.loc[df1['SecuritiesCode'] == col] 
    
    # Feature engineering
    smallest = feature_eng(smallest)
    
    # Split df into train/test
    column_indices = {name: i for i, name in enumerate(smallest.columns)}

    n = len(smallest)
    train_df = smallest[0:int(n*0.85)]
    test_df = smallest[int(n*0.85):]

    num_features = smallest.shape[1]
    
    # split train and test df's for Target
    x_train = train_df.drop('Target', axis=1)
    y_train = train_df['Target']
    x_test = test_df.drop('Target', axis=1)
    y_test = test_df['Target']
    
    # Fit model
    history = model.fit(
    x_train,
    y_train,
    validation_data=(x_test, y_test),
    epochs=params["epochs"],
    batch_size=params["batch_size"],
    verbose=1,
    )
    
    # Generate Predictions
    preds = model.predict(x_test)
    
    # Cread preds df with datetime index from test_df
    preds = pd.DataFrame(data=preds, index=test_df.index)
    
    preds[col] = preds[0]
    preds = preds.drop(0,axis=1)
    
    # Concat df of Predictions
    small_df = pd.concat([small_df, preds], axis=1)
    
small_df

Epoch 1/4
8/8 [==============================] - 2s 245ms/step - loss: 0.0109 - root_mean_squared_error: 0.1043 - mean_absolute_error: 0.0763 - val_loss: 0.0076 - val_root_mean_squared_error: 0.0873 - val_mean_absolute_error: 0.0635
Epoch 2/4
8/8 [==============================] - 2s 241ms/step - loss: 0.0107 - root_mean_squared_error: 0.1032 - mean_absolute_error: 0.0755 - val_loss: 0.0076 - val_root_mean_squared_error: 0.0869 - val_mean_absolute_error: 0.0630
Epoch 3/4
8/8 [==============================] - 2s 193ms/step - loss: 0.0107 - root_mean_squared_error: 0.1035 - mean_absolute_error: 0.0755 - val_loss: 0.0077 - val_root_mean_squared_error: 0.0875 - val_mean_absolute_error: 0.0640
Epoch 4/4
8/8 [==============================] - 2s 189ms/step - loss: 0.0105 - root_mean_squared_error: 0.1025 - mean_absolute_error: 0.0751 - val_loss: 0.0075 - val_root_mean_squared_error: 0.0869 - val_mean_absolute_error: 0.0631
6/6 [==============================] - 0s 26ms/step
Epoch 1/4
8/8 [==============================] - 2s 195ms/step - loss: 0.0110 - root_mean_squared_error: 0.1048 - mean_absolute_error: 0.0750 - val_loss: 0.0086 - val_root_mean_squared_error: 0.0925 - val_mean_absolute_error: 0.0677
Epoch 2/4
8/8 [==============================] - 2s 191ms/step - loss: 0.0107 - root_mean_squared_error: 0.1033 - mean_absolute_error: 0.0752 - val_loss: 0.0086 - val_root_mean_squared_error: 0.0926 - val_mean_absolute_error: 0.0680
Epoch 3/4
8/8 [==============================] - 2s 195ms/step - loss: 0.0109 - root_mean_squared_error: 0.1046 - mean_absolute_error: 0.0757 - val_loss: 0.0085 - val_root_mean_squared_error: 0.0924 - val_mean_absolute_error: 0.0676
Epoch 4/4
8/8 [==============================] - 2s 200ms/step - loss: 0.0110 - root_mean_squared_error: 0.1049 - mean_absolute_error: 0.0764 - val_loss: 0.0087 - val_root_mean_squared_error: 0.0933 - val_mean_absolute_error: 0.0691
6/6 [==============================] - 0s 27ms/step

                1301      1332
Date
2021-03-11  0.480204  0.488863
2021-03-12  0.481915  0.489964
2021-03-15  0.487678  0.488786
2021-03-16  0.486750  0.486910
2021-03-17  0.486003  0.488146
...              ...       ...
2021-11-29  0.481012  0.480776
2021-11-30  0.479702  0.484698
2021-12-01  0.481678  0.487114
2021-12-02  0.482568  0.485703
2021-12-03  0.485539  0.489641

[181 rows x 2 columns]

In [136]:
# Unstack predictions_df
full_preds_pivot = small_df.unstack(level=2)

# Make unstack a df with Target Predictions
full_preds_pivot_df = pd.DataFrame(full_preds_pivot)
full_preds_pivot_df['Target'] = full_preds_pivot_df[0]
full_preds_pivot_df = full_preds_pivot_df.drop(0, axis=1)
full_preds_pivot_df.reset_index(inplace = True, drop = False)
full_preds_pivot_df['SecuritiesCode'] = full_preds_pivot_df['level_0']
full_preds_pivot_df = full_preds_pivot_df.drop('level_0', axis=1)

# Rank Securities Codes by Target
full_preds_pivot_df = full_preds_pivot_df.sort_values(by = ["Date",'Target'], ascending = True)
full_preds_pivot_df['RANK'] = full_preds_pivot_df.groupby('Date')['SecuritiesCode'].rank(ascending=False)-1

# Drop Target
full_preds_pivot_df = full_preds_pivot_df.drop('Target', axis=1)

full_preds_pivot_df

          Date  SecuritiesCode  RANK
0   2021-03-11            1301   1.0
181 2021-03-11            1332   0.0
1   2021-03-12            1301   1.0
182 2021-03-12            1332   0.0
2   2021-03-15            1301   1.0
..         ...             ...   ...
359 2021-12-01            1332   0.0
179 2021-12-02            1301   1.0
360 2021-12-02            1332   0.0
180 2021-12-03            1301   1.0
361 2021-12-03            1332   0.0

[362 rows x 3 columns]

# Practice Submission

In [35]:
df_test

,RowId,Date,SecuritiesCode,Open,High,Low,Close,Volume,AdjustmentFactor,ExpectedDividend,SupervisionFlag
0,20211206_1301,2021-12-06,1301,2982.0,2982.0,2965.0,2971.0,8900,1.0,NaN,False
1,20211206_1332,2021-12-06,1332,592.0,599.0,588.0,589.0,1360800,1.0,NaN,False
2,20211206_1333,2021-12-06,1333,2368.0,2388.0,2360.0,2377.0,125900,1.0,NaN,False
3,20211206_1375,2021-12-06,1375,1230.0,1239.0,1224.0,1224.0,81100,1.0,NaN,False
4,20211206_1376,2021-12-06,1376,1339.0,1372.0,1339.0,1351.0,6200,1.0,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...
195988,20220428_9990,2022-04-28,9990,497.0,504.0,494.0,504.0,51900,1.0,NaN,False
195989,20220428_9991,2022-04-28,9991,776.0,786.0,774.0,784.0,23400,1.0,NaN,False
195990,20220428_9993,2022-04-28,9993,1520.0,1530.0,1510.0,1517.0,8100,1.0,NaN,False
195991,20220428_9994,2022-04-28,9994,2471.0,2489.0,2457.0,2485.0,7800,1.0,NaN,False
195992,20220428_9997,2022-04-28,9997,717.0,731.0,714.0,731.0,149800,1.0,NaN,False

In [45]:
df_test = prices_2.drop('Target', axis=1)

# Create prediction df
check_please = df_test.loc[df_test['SecuritiesCode'] == col]
    
        ##
check_please = featuring(check_please)
check_please

,Open,High,Low,Close,Volume,High_lag_1,Open_lag_1,Close_lag_1,Volume_lag_1,Low_lag_1,Daily_Spread,Daily_Max_Min,1_Day_Spread,2_Day_Spread,1_Week_Spread,MA_Prior_1day,MA_Prior_2day,MA_Prior_diff,ExPost_SR
Date,,,,,,,,,,,,,,,,,,,
2021-12-06,1.000000,1.000000,1.000000,1.000000,0.089671,0.000000,0.000000,0.000000,0.000000,0.000000,0.250,0.225806,0.478261,0.493506,0.471074,1.000000,1.000000,0.293103,0.106796
2021-12-07,0.750000,0.680851,0.417582,0.633333,0.935102,1.000000,1.000000,1.000000,0.296946,1.000000,0.000,0.967742,0.000000,0.493506,0.471074,0.594203,0.714286,0.189655,0.203883
2021-12-08,0.608696,0.574468,0.516484,0.577778,0.454268,0.974958,0.980574,0.971986,0.852127,0.954932,0.200,0.354839,0.405797,0.000000,0.471074,0.681159,0.740260,0.258621,0.368932
2021-12-09,0.576087,0.531915,0.472527,0.455556,0.247778,0.961052,0.966774,0.959813,0.826683,0.945017,0.000,0.354839,0.318841,0.285714,0.471074,0.623188,0.610390,0.362069,0.388350
2021-12-10,0.391304,0.393617,0.351648,0.377778,0.343263,0.952421,0.958615,0.949066,0.746162,0.938350,0.250,0.290323,0.376812,0.259740,0.471074,0.536232,0.571429,0.310345,0.378641
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-04-22,0.728261,0.702128,0.659341,0.766667,0.143918,0.942404,0.944257,0.952462,0.338036,0.941752,0.350,0.322581,0.376812,0.454545,0.578512,0.608696,0.519481,0.465517,0.349515
2022-04-25,0.652174,0.659574,0.681319,0.700000,0.032117,0.950751,0.951436,0.961375,0.380140,0.948554,0.375,0.129032,0.391304,0.324675,0.595041,0.449275,0.545455,0.241379,0.281553
2022-04-26,0.706522,0.755319,0.747253,0.755556,0.078887,0.956594,0.955236,0.966044,0.377298,0.954082,0.375,0.225806,0.550725,0.480519,0.603306,0.637681,0.415584,0.637931,0.378641
2022-04-27,0.684783,0.670213,0.659341,0.666667,0.061924,0.958264,0.959037,0.964346,0.324725,0.958333,0.225,0.225806,0.362319,0.454545,0.371901,0.304348,0.506494,0.120690,0.014563
2022-04-28,0.695652,0.734043,0.714286,0.833333,0.123498,0.952421,0.952280,0.957555,0.283209,0.951531,0.575,0.258065,0.695652,0.584416,0.462810,0.521739,0.506494,0.379310,0.378641

In [46]:
check_please = np.expand_dims(np.array(check_please), 2)
check_please.shape

(98, 19, 1)

In [24]:
df_test = prices_2.drop('Target', axis=1)

In [41]:
#col_list = prices['SecuritiesCode'].values.tolist()
small_df = pd.DataFrame()

for col in small_col_list:
        # Pull one stock's values for given stock from stock_prices
    smallest = prices.loc[prices['SecuritiesCode'] == col] 

        # Feature engineering
    smallest = feature_eng(smallest)

        # Split df into train/test
    column_indices = {name: i for i, name in enumerate(smallest.columns)}

    n = len(smallest)
    train_df = smallest[0:int(n*0.85)]
    test_df = smallest[int(n*0.85):]

        # split train and test df's for Target
    x_train = train_df.drop('Target', axis=1)
    y_train = train_df['Target']
    x_test = test_df.drop('Target', axis=1)
    y_test = test_df['Target']

        # Add dimension and convert to np.array
    x_train, y_train = np.expand_dims(np.array(x_train), 2), np.expand_dims(np.expand_dims(np.array(y_train),1), 1)
    x_test, y_test = np.expand_dims(np.array(x_test), 2), np.expand_dims(np.expand_dims(np.array(y_test),1), 1)

        # Fit model
    history = model.fit(
    x_train,
    y_train,
    validation_data=(x_test, y_test),
    epochs=params["epochs"],
    batch_size=params["batch_size"],
    verbose=1,
    )
        
        # Create prediction df
    check_please = df_test.loc[df_test['SecuritiesCode'] == col]
    
        ##
    check_please = featuring(check_please)
        
        # Generate Predictions
    preds = model.predict(check_please)

        # Cread preds df with datetime index from test_df
    preds = pd.DataFrame(data=preds, index=check_please.index)

    preds[col] = preds[0]
    preds = preds.drop(0,axis=1)

        # Concat df of Predictions
    small_df = pd.concat([small_df, preds], axis=1)
    
    # Unstack predictions_df
full_preds_pivot = small_df.unstack(level=2)

    # Make unstack a df with Target Predictions
full_preds_pivot_df = pd.DataFrame(full_preds_pivot)
full_preds_pivot_df['Target'] = full_preds_pivot_df[0]
full_preds_pivot_df = full_preds_pivot_df.drop(0, axis=1)
full_preds_pivot_df.reset_index(inplace = True, drop = False)
full_preds_pivot_df['SecuritiesCode'] = full_preds_pivot_df['level_0']
full_preds_pivot_df = full_preds_pivot_df.drop('level_0', axis=1)

    # Rank Securities Codes by Target
full_preds_pivot_df = full_preds_pivot_df.sort_values(by = ["Date",'Target'], ascending = True)
full_preds_pivot_df['RANK'] = full_preds_pivot_df.groupby('Date')['SecuritiesCode'].rank(ascending=False)-1

    # Drop Target
submission = full_preds_pivot_df.drop('Target', axis=1)
    
submission

Epoch 1/4
8/8 [==============================] - 2s 235ms/step - loss: 0.0104 - root_mean_squared_error: 0.1018 - mean_absolute_error: 0.0743 - val_loss: 0.0076 - val_root_mean_squared_error: 0.0869 - val_mean_absolute_error: 0.0626
Epoch 2/4
8/8 [==============================] - 2s 208ms/step - loss: 0.0109 - root_mean_squared_error: 0.1045 - mean_absolute_error: 0.0779 - val_loss: 0.0078 - val_root_mean_squared_error: 0.0886 - val_mean_absolute_error: 0.0642
Epoch 3/4
8/8 [==============================] - 2s 205ms/step - loss: 0.0105 - root_mean_squared_error: 0.1027 - mean_absolute_error: 0.0745 - val_loss: 0.0077 - val_root_mean_squared_error: 0.0879 - val_mean_absolute_error: 0.0635
Epoch 4/4
8/8 [==============================] - 2s 242ms/step - loss: 0.0109 - root_mean_squared_error: 0.1046 - mean_absolute_error: 0.0760 - val_loss: 0.0086 - val_root_mean_squared_error: 0.0927 - val_mean_absolute_error: 0.0683
4/4 [==============================] - 0s 34ms/step
Epoch 1/4
8/8 [==============================] - 2s 210ms/step - loss: 0.0110 - root_mean_squared_error: 0.1049 - mean_absolute_error: 0.0776 - val_loss: 0.0088 - val_root_mean_squared_error: 0.0940 - val_mean_absolute_error: 0.0686
Epoch 2/4
8/8 [==============================] - 2s 205ms/step - loss: 0.0113 - root_mean_squared_error: 0.1064 - mean_absolute_error: 0.0777 - val_loss: 0.0086 - val_root_mean_squared_error: 0.0929 - val_mean_absolute_error: 0.0677
Epoch 3/4
8/8 [==============================] - 2s 203ms/step - loss: 0.0108 - root_mean_squared_error: 0.1040 - mean_absolute_error: 0.0751 - val_loss: 0.0086 - val_root_mean_squared_error: 0.0927 - val_mean_absolute_error: 0.0681
Epoch 4/4
8/8 [==============================] - 2s 207ms/step - loss: 0.0110 - root_mean_squared_error: 0.1049 - mean_absolute_error: 0.0761 - val_loss: 0.0086 - val_root_mean_squared_error: 0.0926 - val_mean_absolute_error: 0.0680
4/4 [==============================] - 0s 25ms/step

          Date  SecuritiesCode  RANK
0   2021-12-06            1301   1.0
98  2021-12-06            1332   0.0
1   2021-12-07            1301   1.0
99  2021-12-07            1332   0.0
2   2021-12-08            1301   1.0
..         ...             ...   ...
193 2022-04-26            1332   0.0
96  2022-04-27            1301   1.0
194 2022-04-27            1332   0.0
97  2022-04-28            1301   1.0
195 2022-04-28            1332   0.0

[196 rows x 3 columns]

In [40]:
small_df

Empty DataFrame
Columns: []
Index: []